import "bootstrap/dist/css/bootstrap.min.css";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" style={{ height: "100%" }}>
      <body style={{ height: "100%" }}>
        {children}
      </body>
    </html >
  )
}

// import "bootstrap/dist/css/bootstrap.min.css";
// import ImportBsJS from "../components/importBsJS";
// import { Nav, Navbar, Container } from "react-bootstrap";

// export default function RootLayout({
//     children,
// }: {
//     children: React.ReactNode;
// }) {
//     return (
//         <>
//             <html lang="en" style={{ height: "100%" }}>
//                 <body style={{ height: "100%" }}>
//                     <ImportBsJS />
//                     <Navbar bg="primary" expand="lg">
//                         <Container fluid={true}>
//                             <a className="navbar-brand text-white" href="#">Dimeviz</a>
//                         </Container>
//                     </Navbar>
//                     <Container fluid={true}>
//                         <div className="content mt-3">
//                             {children}
//                         </div>
//                     </Container>
//                 </body>
//             </html>
//         </>
//     );
// }



